"""empty message

Revision ID: 3b9a84c25d6a
Revises: 
Create Date: 2025-05-31 20:46:12.897612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b9a84c25d6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demografia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wojewodztwo', sa.String(), nullable=True),
    sa.Column('rok', sa.Integer(), nullable=True),
    sa.Column('liczba_ludnosci', sa.Integer(), nullable=True),
    sa.Column('kobiety', sa.Integer(), nullable=True),
    sa.Column('mezczyzni', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demografia_id'), 'demografia', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_demografia_id'), table_name='demografia')
    op.drop_table('demografia')
    # ### end Alembic commands ###
