"""empty message

Revision ID: 94fe231fb1ca
Revises: 1f6cb76e48f3
Create Date: 2025-06-04 19:49:52.511129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94fe231fb1ca'
down_revision = '1f6cb76e48f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ludnosc_woj',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wojewodztwa', sa.String(), nullable=True),
    sa.Column('rok', sa.Integer(), nullable=True),
    sa.Column('liczba_ludnosci', sa.Integer(), nullable=True),
    sa.Column('kobiety', sa.Integer(), nullable=True),
    sa.Column('mezczyzni', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ludnosc_woj_id'), 'ludnosc_woj', ['id'], unique=False)
    op.drop_column('zgony_woj', 'kobiety')
    op.drop_column('zgony_woj', 'mezczyzni')
    op.drop_column('zgony_woj', 'liczba_ludnosci')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zgony_woj', sa.Column('liczba_ludnosci', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('zgony_woj', sa.Column('mezczyzni', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('zgony_woj', sa.Column('kobiety', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_ludnosc_woj_id'), table_name='ludnosc_woj')
    op.drop_table('ludnosc_woj')
    # ### end Alembic commands ###
